version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - "C-Dependencies"
    groups:
      wgpu:
        patterns:
          - "*wgpu*"
          - "naga*"
      accesskit:
        patterns:
          - "accesskit*"
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "C-Dependencies"
    cooldown:
      default-days: 7
